package com.demo.pet.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Abstract base class for all model entities in the Pet Clinic system.
 * <p>
 * Provides common fields such as id, createdAt, and updatedAt for entity tracking.
 * Handles automatic timestamp management for creation and updates.
 * </p>
 *
 * @since 1.0
 */
@Getter
@Setter
@MappedSuperclass
public abstract class BaseModel {
    /**
     * Primary key identifier for the entity.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Timestamp when the entity was created.
     * Automatically set on persist.
     */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /**
     * Timestamp when the entity was last updated.
     * Automatically updated on change.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Sets creation and update timestamps before persisting the entity.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Updates the timestamp before updating the entity.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
